CREATE TEMPORARY TABLE t LIKE Path;
INSERT INTO t 
SELECT DISTINCT * FROM Path;

TRUNCATE Path;

INSERT INTO Path 
SELECT DISTINCT * FROM t;

ALTER TABLE Path ADD PRIMARY KEY (root_id, target_id, parent_id);

